Repository U6D5T4/Auctionify, pull requests merged in 2024-01, with the labels that each got.

#88 [40] - View active auctions (buyer)
  src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.html
  src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.scss
  src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.ts
  src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.ts
  src/Auctionify.API/ClientApp/src/app/web-api-client.ts
  src/Auctionify.API/ClientApp/src/assets/icons/ArrowNarrowRightIcon.svg
  src/Auctionify.API/ClientApp/src/assets/icons/AuctionIcon.svg
  src/Auctionify.API/Controllers/UsersController.cs
  src/Auctionify.Application/Features/Users/Profiles/MappingProfiles.cs
  src/Auctionify.Application/Features/Users/Queries/GetBuyerAuctions/GetBuyerAuctionsQuery.cs
  src/Auctionify.Application/Features/Users/Queries/GetBuyerAuctions/GetBuyerAuctionsResponse.cs
  src/Auctionify.Application/Features/Users/Queries/GetWatchlistLots/GetWatchlistLotsQuery.cs
  src/Auctionify.Application/Features/Users/Queries/GetWatchlistLots/GetWatchlistLotsResponse.cs
  src/Auctionify.Application/Scheduler/Jobs/FinishLotJob.cs
  src/Auctionify.Core/Persistence/Paging/IEnumerablePaginateExtensions.cs
  tests/Auctionify.UnitTests/GetBuyerAuctionsTests/GetBuyerAuctionsQueryHandlerTests.cs
  tests/Auctionify.UnitTests/GetWatshlistLotsTests/GetWatchlistLotsQueryHandlerTests.cs
Labels: enhancement, fixes

#90 [150] - December Demo Bugs
  src/Auctionify.API/ClientApp/src/app/api-authorization/email-sent/email-sent.component.html
  src/Auctionify.API/ClientApp/src/app/api-authorization/email-sent/email-sent.component.scss
  src/Auctionify.API/ClientApp/src/app/api-authorization/forget-password/forget-password.component.html
  src/Auctionify.API/ClientApp/src/app/api-authorization/forget-password/forget-password.component.scss
  src/Auctionify.API/ClientApp/src/app/api-authorization/login/login.component.html
  src/Auctionify.API/ClientApp/src/app/api-authorization/login/login.component.scss
  src/Auctionify.API/ClientApp/src/app/api-authorization/register-role/register-role.component.html
  src/Auctionify.API/ClientApp/src/app/api-authorization/register-role/register-role.component.scss
  src/Auctionify.API/ClientApp/src/app/api-authorization/register/register.component.html
  src/Auctionify.API/ClientApp/src/app/api-authorization/register/register.component.scss
  src/Auctionify.API/ClientApp/src/app/api-authorization/reset-password/reset-password.component.html
  src/Auctionify.API/ClientApp/src/app/api-authorization/reset-password/reset-password.component.scss
  src/Auctionify.API/ClientApp/src/app/app.component.html
  src/Auctionify.API/ClientApp/src/app/app.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/add-bid/add-bid.component.ts
  src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.html
  src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.ts
  src/Auctionify.API/ClientApp/src/app/components/general/profile/change-password/change-password.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/profile/update-user-profile/update-user-profile.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/profile/user-profile/user-profile.component.scss
  src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/create-lot.component.scss
  src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/pop-ups/currency/currency.component.html
  src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/pop-ups/currency/currency.component.ts
  src/Auctionify.API/ClientApp/src/app/layout/footer/footer.component.scss
  src/Auctionify.API/ClientApp/src/app/layout/header/header.component.scss
  src/Auctionify.API/ClientApp/src/styles.scss
  src/Auctionify.Infrastructure/Data/Config/BidConfiguration.cs
  src/Auctionify.Infrastructure/Data/Config/LotConfiguration.cs
Labels: fixes

#93 FE fixes in dev
  src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.html
  src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.scss
Labels: fixes

#91 [33] - View transactions history (buyer + seller)
  src/Auctionify.API/ClientApp/src/app/app-routing.module.ts
  src/Auctionify.API/ClientApp/src/app/components/buyer/buyer.module.ts
  src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.html
  src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/general.module.ts
  src/Auctionify.API/ClientApp/src/app/components/general/transactions/transactions.component.html
  src/Auctionify.API/ClientApp/src/app/components/general/transactions/transactions.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/transactions/transactions.component.spec.ts
  src/Auctionify.API/ClientApp/src/app/components/general/transactions/transactions.component.ts
  src/Auctionify.API/ClientApp/src/app/components/seller/dashboard/dashboard.component.html
  src/Auctionify.API/ClientApp/src/app/components/seller/dashboard/dashboard.component.scss
  src/Auctionify.API/ClientApp/src/app/components/seller/seller.module.ts
  src/Auctionify.API/ClientApp/src/app/web-api-client.ts
  src/Auctionify.API/ClientApp/src/styles.scss
  src/Auctionify.API/Controllers/UsersController.cs
  src/Auctionify.Application/Common/Models/Transaction/TransactionInfo.cs
  src/Auctionify.Application/Features/Users/Profiles/MappingProfiles.cs
  src/Auctionify.Application/Features/Users/Queries/GetTransactions/GetTransactionsUserQuery.cs
  src/Auctionify.Application/Features/Users/Queries/GetTransactions/GetTransactionsUserResponse.cs
  src/Auctionify.Application/Features/Users/Queries/GetWatchlistLots/GetWatchlistLotsQuery.cs
  src/Auctionify.Core/Enums/BuyerTransactionStatus.cs
  src/Auctionify.Core/Enums/SellerTransactionStatus.cs
  tests/Auctionify.UnitTests/EntitiesSeeding.cs
  tests/Auctionify.UnitTests/GetTransactionsTests/GetTransactionsUserQueryHandlerTests.cs
  tests/Auctionify.UnitTests/GetTransactionsTests/TransactionTestData.cs
Labels: enhancement

#97 [153], [154], [156], [157] fixes (bugfix tickets)
  src/Auctionify.API/ClientApp/src/app/components/buyer/dashboard/dashboard.component.ts
  src/Auctionify.API/ClientApp/src/app/components/buyer/wishlist/wishlist.component.ts
  src/Auctionify.API/ClientApp/src/app/components/general/add-bid/add-bid.component.html
  src/Auctionify.API/ClientApp/src/app/components/general/add-bid/add-bid.component.ts
  src/Auctionify.API/ClientApp/src/app/components/general/home/auction/auction.component.ts
  src/Auctionify.API/ClientApp/src/app/components/general/lot-profile/lot-profile.component.ts
  src/Auctionify.API/ClientApp/src/app/components/general/profile/update-user-profile/update-user-profile.component.html
  src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.html
  src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.scss
  src/Auctionify.API/ClientApp/src/app/components/general/remove-from-watchlist/remove-from-watchlist.component.ts
  src/Auctionify.API/ClientApp/src/app/components/general/withdraw-bid/withdraw-bid.component.html
  src/Auctionify.API/ClientApp/src/app/components/seller/create-lot/create-lot.component.ts
  src/Auctionify.API/ClientApp/src/app/layout/header/header.component.ts
Labels: enhancement, fixes

#101 [165] - Update list of lots categories
  src/Auctionify.Infrastructure/Persistence/ApplicationDbContextInitializer.cs
Labels: enhancement, fixes

#96 [152] - Send message and SignalR hub (All Backend for Chats)
  src/Auctionify.API/Controllers/ChatsController.cs
  src/Auctionify.Application/Auctionify.Application.csproj
  src/Auctionify.Application/Common/Models/UserConversations/ChatUser.cs
  src/Auctionify.Application/Common/Models/UserConversations/User.cs
  src/Auctionify.Application/Features/Chats/Commands/CreateChatMessage/CreateChatMessageCommand.cs
  src/Auctionify.Application/Features/Chats/Commands/CreateChatMessage/CreateChatMessageCommandValidator.cs
  src/Auctionify.Application/Features/Chats/Commands/CreateChatMessage/CreatedChatMessageResponse.cs
  src/Auctionify.Application/Features/Chats/Commands/CreateConversation/CreateConversationCommand.cs
  src/Auctionify.Application/Features/Chats/Commands/CreateConversation/CreateConversationCommandValidator.cs
  src/Auctionify.Application/Features/Chats/Commands/CreateConversation/CreatedConversationResponse.cs
  src/Auctionify.Application/Features/Chats/Commands/MarkChatMessageAsRead/MarkChatMessageAsReadCommand.cs
  src/Auctionify.Application/Features/Chats/Commands/MarkChatMessageAsRead/MarkChatMessageAsReadCommandValidator.cs
  src/Auctionify.Application/Features/Chats/Commands/MarkChatMessageAsRead/MarkedChatMessageAsReadResponse.cs
  src/Auctionify.Application/Features/Chats/Profiles/MappingProfiles.cs
  src/Auctionify.Application/Features/Chats/Queries/GetAllUserConversations/GetAllUserConversationsQuery.cs
  src/Auctionify.Application/Hubs/AuctionHub.cs
  src/Auctionify.Application/Hubs/SignalRActions.cs
  src/Auctionify.Application/Scheduler/Jobs/FinishLotJob.cs
  src/Auctionify.Infrastructure/Migrations/20240111103755_RateTableTypoFix.Designer.cs
  src/Auctionify.Infrastructure/Migrations/20240111103755_RateTableTypoFix.cs
  src/Auctionify.Infrastructure/Migrations/20240125084038_RateTableFixAndChatWithConversationTableSetup.Designer.cs
  src/Auctionify.Infrastructure/Migrations/20240125084038_RateTableFixAndChatWithConversationTableSetup.cs
  src/Auctionify.Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
  tests/Auctionify.UnitTests/CreateChatMessageTests/CreateChatMessageCommandHandlerTests.cs
  tests/Auctionify.UnitTests/CreateConversationTests/CreateConversationCommandHandlerTests.cs
  tests/Auctionify.UnitTests/MarkChatMessageAsReadTests/MarkChatMessageAsReadCommandHandlerTests.cs
Labels: enhancement, fixes
